# Singular Value Decomposition

generate 100x1000 matrix, get principle components

In [1]:
import numpy as np

In [4]:
vector1 = np.random.randint(-100, 101, size=1000)
vector2 = 2 * vector1
vector3 = np.random.randint(-100, 101, size=1000)
vector4 = -3 * vector3
vector5 = np.random.randint(-100, 101, size=1000)
vector6 = 1 * vector5
vector7 = np.random.randint(-100, 101, size=1000)
vector8 = 4 * vector7
vector9 = np.random.randint(-100, 101, size=1000)
vector10 = -2 * vector9

matrix_part1 = np.array([vector1, vector2, vector3, vector4, vector5, vector6, vector7, vector8, vector9, vector10])
matrix_part2 = np.random.randint(-20, 21, size=(45, 1000))
matrix_part3 = np.random.randint(-5, 6, size=(45, 1000))

A = np.vstack((matrix_part1, matrix_part2, matrix_part3)).T

U, s, V = np.linalg.svd(A, full_matrices=True)
s

array([7.64116709e+03, 5.79681128e+03, 4.19184968e+03, 4.12181153e+03,
       2.66495183e+03, 4.48685431e+02, 4.40586989e+02, 4.33974938e+02,
       4.30493626e+02, 4.27254643e+02, 4.24349784e+02, 4.20033052e+02,
       4.15975049e+02, 4.09588186e+02, 4.06915813e+02, 4.04799826e+02,
       4.02217200e+02, 3.98278479e+02, 3.96232983e+02, 3.93222432e+02,
       3.91484390e+02, 3.90875558e+02, 3.85274716e+02, 3.83518670e+02,
       3.79081040e+02, 3.76945378e+02, 3.74690018e+02, 3.70653743e+02,
       3.68811505e+02, 3.64956646e+02, 3.64051779e+02, 3.58727335e+02,
       3.57905683e+02, 3.53160278e+02, 3.49905580e+02, 3.48456601e+02,
       3.47120837e+02, 3.45171646e+02, 3.40387359e+02, 3.39167367e+02,
       3.36221083e+02, 3.34873252e+02, 3.29337141e+02, 3.27069127e+02,
       3.22333910e+02, 3.17687592e+02, 3.13368377e+02, 3.11754605e+02,
       3.06637950e+02, 2.98484188e+02, 1.15199226e+02, 1.14171163e+02,
       1.12820833e+02, 1.11891789e+02, 1.10521120e+02, 1.10223028e+02,
      

In [35]:
ranarray = np.random.randint(-10, 11, size=(10, 3))

array = np.array([[1, 1], [1, 1], [0, 0]])

U, s, V = np.linalg.svd(array, full_matrices=True)
print(U)
print(s)
print(V)
x_t = U @ np.array([[2, 0], [0, 0], [0, 0]]) @ V
print(x_t)

[[-0.70710678 -0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
[2.00000000e+00 3.35470445e-17]
[[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]
[[1. 1.]
 [1. 1.]
 [0. 0.]]


# 데이터 생성 방법
### 100 차원 벡터 1000개로 이루어진 행렬 (1000 x 100)

#### 조건: 10개 (2개씩 짝지어 5쌍 일차식 관계), 45개 (-20, 20 범위 랜덤), 45개 (-5, 5 범위 랜덤)

1. 1000 차원의 벡터를 5개 생성한다(-100, 100 범위). 특정 상수를 각각 곱해서 5개 더 생성한다
2. 1000 차원의 벡터를 -20, 20 범위로 45개 생성한다.
3. 1000 차원의 벡터를 -5, 5 범위로 45개 생성한다.

모든 벡터를 더해서 행렬(100 x 1000)을 만든다. 그 행렬을 전치해서 행렬 A(1000 x 100)을 만든다.

In [26]:
vector1 = np.random.randint(-100, 101, size=1000)
vector2 = 2 * vector1
vector3 = np.random.randint(-100, 101, size=1000)
vector4 = -3 * vector3
vector5 = np.random.randint(-100, 101, size=1000)
vector6 = 1 * vector5
vector7 = np.random.randint(-100, 101, size=1000)
vector8 = 4 * vector7
vector9 = np.random.randint(-100, 101, size=1000)
vector10 = -2 * vector9

matrix_part1 = np.array([vector1, vector2, vector3, vector4, vector5, vector6, vector7, vector8, vector9, vector10])
matrix_part2 = np.random.randint(-20, 21, size=(45, 1000))
matrix_part3 = np.random.randint(-5, 6, size=(45, 1000))

A = np.vstack((matrix_part1, matrix_part2, matrix_part3)).T

U, s, V = np.linalg.svd(A, full_matrices=True)

In [27]:
vector1 = np.random.randint(-100, 101, size=1)
vector2 = 2 * vector1
vector3 = np.random.randint(-100, 101, size=1)
vector4 = -3 * vector3
vector5 = np.random.randint(-100, 101, size=1)
vector6 = 1 * vector5
vector7 = np.random.randint(-100, 101, size=1)
vector8 = 4 * vector7
vector9 = np.random.randint(-100, 101, size=1)
vector10 = -2 * vector9

matrix_part1 = np.array([vector1, vector2, vector3, vector4, vector5, vector6, vector7, vector8, vector9, vector10])
matrix_part2 = np.random.randint(-20, 21, size=(45, 1))
matrix_part3 = np.random.randint(-5, 6, size=(45, 1))

X_set = np.vstack((matrix_part1, matrix_part2, matrix_part3)).T
X_set

array([[  34,   68,   62, -186,   84,   84,  -53, -212,   88, -176,  -11,
          -2,    5,  -16,   20,   14,    8,  -14,  -12,  -20,   -2,   -3,
          -1,  -17,  -13,    8,   19,    7,    4,   16,   -4,    1,   16,
          -2,  -18,    3,    2,   -5,    6,   13,  -13,   10,   -8,   16,
          -4,  -15,  -20,  -18,  -16,   15,   15,  -16,   20,   12,    0,
          -3,    1,   -5,    2,    5,    5,    3,   -5,    0,   -1,   -1,
           0,   -5,   -4,   -4,    4,    4,   -1,    5,    0,    2,   -1,
           4,   -4,    1,   -1,   -3,   -3,    2,   -5,   -2,    3,   -2,
          -2,   -1,    1,    3,    2,   -1,   -4,   -4,    5,    0,    5,
           3]])

In [33]:
np.round(V[0], 3)

array([ 0.004,  0.007,  0.034, -0.103,  0.003,  0.003, -0.241, -0.964,
        0.007, -0.013, -0.   ,  0.001, -0.001, -0.   ,  0.002,  0.   ,
        0.   , -0.002,  0.001, -0.001, -0.001, -0.   ,  0.002,  0.001,
        0.001,  0.   ,  0.001, -0.   , -0.001, -0.001,  0.001, -0.001,
        0.   , -0.001, -0.   ,  0.003, -0.002,  0.002,  0.001,  0.   ,
       -0.002, -0.001, -0.001,  0.001,  0.001, -0.002, -0.002,  0.003,
        0.001, -0.001,  0.002, -0.001, -0.001, -0.004,  0.   , -0.   ,
        0.001, -0.001, -0.   , -0.001,  0.001, -0.   ,  0.   ,  0.   ,
       -0.   , -0.001, -0.   , -0.001, -0.   ,  0.   , -0.001, -0.   ,
       -0.   , -0.   ,  0.   , -0.   , -0.   ,  0.001, -0.   ,  0.001,
        0.001, -0.   , -0.   , -0.   , -0.   , -0.001,  0.   ,  0.   ,
       -0.   , -0.   , -0.001, -0.   , -0.   , -0.   , -0.001, -0.   ,
       -0.   , -0.   , -0.   ,  0.   ])

In [30]:
X_hat = np.zeros(100)
for i in range(95):
    X_hat = X_hat + np.dot(X_set, V[i]) * V[i]
for e in X_hat:
    print(e)

34.000000000000036
68.00000000000021
61.999999999999865
-186.00000000000006
83.99999999999984
83.99999999999994
-52.99999999999996
-212.0
87.99999999999989
-175.99999999999986
-11.000000000000018
-2.000000000000008
4.999999999999994
-15.999999999999979
20.000000000000025
14.000000000000007
8.000000000000025
-14.000000000000037
-11.99999999999997
-20.00000000000001
-1.9999999999999976
-3.000000000000002
-1.000000000000018
-17.00000000000003
-12.99999999999998
8.0
18.99999999999998
7.0000000000000115
4.000000000000026
16.000000000000032
-4.00000000000003
0.9999999999999738
16.000000000000004
-1.9999999999999867
-17.999999999999996
3.0000000000000075
1.9999999999999798
-5.000000000000003
6.000000000000023
12.999999999999973
-13.000000000000007
9.99999999999998
-8.000000000000002
15.999999999999977
-3.9999999999999862
-15.000000000000027
-19.999999999999964
-17.999999999999993
-15.99999999999998
14.99999999999997
15.0
-16.0
19.99999999999997
12.00000000000002
-1.5286166429873127e-14
-2.999

In [52]:
def calculate_distance(X, r):
    X_hat = np.zeros(100)
    for i in range(r):
        X_hat = X_hat + np.dot(X, V[i]) * V[i]

    dist = np.linalg.norm(X - X_hat)
    return dist

In [56]:
for r in range(10, 100, 5):
    dist_total = 0
    for X in X_set:
        dist_total += calculate_distance(X, r)
    print(dist_total/100)

77.67682540718322
73.05560058995248
67.70413942171216
62.209145270264486
56.358310682513995
50.095642176245775
43.10621964282794
33.87763794112904
22.024183419259977
20.769587686204858
19.4203239164487
17.886557600525695
16.489006979481715
14.741286151993524
12.659538836626668
10.214761344832853
7.053553084294212
4.0177063419724207e-13


In [53]:
for r in range(10, 100, 5):
    dist_total = 0
    for X in X_set:
        dist_total += calculate_distance(X, r)
    print(dist_total/100)

77.97506960174618
73.15759105351937
68.30661038343618
62.91890450374549
56.76361894865039
49.82142425168981
42.58842874058084
33.20196091360427
21.626841423236534
20.470154612899883
19.057652248118046
17.640568791339646
15.992719238805432
14.208327878540127
12.277226006890425
9.731357664377512
6.8107110256701935
4.121539975902939e-13


In [44]:
X_hat = np.zeros(100)
for i in range(95):
    X_hat = X_hat + np.dot(X, V[i]) * V[i]
    
dist = np.linalg.norm(X - X_hat)
print(dist)

3.9254887119268473e-13


In [18]:
array = np.array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

array[0:, 0:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]])